// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGHyiwoQlrXyO9SZ-ni3l6Ej35XiZ8-F4',
    appId: '1:1094317271941:web:9aa4129a0e712fe22a72ec',
    messagingSenderId: '1094317271941',
    projectId: 'locked-in-app',
    authDomain: 'locked-in-app.firebaseapp.com',
    storageBucket: 'locked-in-app.appspot.com',
    measurementId: 'G-M4GKVMYFDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfE7DJ10WiEjW-iK1yR-RjnnL_bqLDdzs',
    appId: '1:1094317271941:android:2325cde06f9d57bf2a72ec',
    messagingSenderId: '1094317271941',
    projectId: 'locked-in-app',
    storageBucket: 'locked-in-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAz7wCqEEaWZWddROI5TzsLf6Hl_hKh60',
    appId: '1:1094317271941:ios:6ac8fe26549ed6412a72ec',
    messagingSenderId: '1094317271941',
    projectId: 'locked-in-app',
    storageBucket: 'locked-in-app.appspot.com',
    iosBundleId: 'com.example.newWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAz7wCqEEaWZWddROI5TzsLf6Hl_hKh60',
    appId: '1:1094317271941:ios:6ac8fe26549ed6412a72ec',
    messagingSenderId: '1094317271941',
    projectId: 'locked-in-app',
    storageBucket: 'locked-in-app.appspot.com',
    iosBundleId: 'com.example.newWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGHyiwoQlrXyO9SZ-ni3l6Ej35XiZ8-F4',
    appId: '1:1094317271941:web:ebbba727ff787d3d2a72ec',
    messagingSenderId: '1094317271941',
    projectId: 'locked-in-app',
    authDomain: 'locked-in-app.firebaseapp.com',
    storageBucket: 'locked-in-app.appspot.com',
    measurementId: 'G-HELSSR9ZXK',
  );
}
